version: "3"
services:
    hey:
        build: .
        container_name: benchmark-client
        restart: 'no'
        ports:
            - 8080:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "16"
                    memory: 32g
    base:
        image: golang:1.14-alpine
        container_name: benchmark-base
        restart: 'no'
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1g
        entrypoint: ["sh","-c","while sleep 3600; do :; done"]
networks:
    app-network:
        driver: bridge
