version: "3"
services:
    hey:
        image: alpine:3.12
        container_name: benchmark-client
        restart: unless-stopped
        ports:
            - 8080:8080
        # command: sh -c "
        #         apk add hey 
        #         && hey -n 1000 -c 1000 -m GET http://nginx"
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
