version: "3"
services:
    hey:
        build: .
        container_name: benchmark-client
        restart: 'no'
        ports:
            - 8080:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "10"
                    memory: 24g
        depends_on:
            - nginx
    base:
        image: golang:1.14-alpine
        container_name: benchmark-base
        restart: 'no'
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1g
        entrypoint: ["sh","-c","while sleep 3600; do :; done"]
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "6"
                    memory: 12g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
