version: "3"
services:
    hey:
        build: .
        container_name: benchmark-client
        restart: 'no'
        ports:
            - 8080:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
