version: "3"
services:
    client:
        container_name: benchmark-client
        image: quaddo/artillery:latest
        restart: "no"
        ports:
            - 8080:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "16"
                    memory: 32g
        entrypoint: ["sh", "-c", "while sleep 3600; do :; done"]
    base:
        image: quaddo/artillery:latest
        container_name: benchmark-base
        restart: "no"
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1g
        entrypoint: ["sh", "-c", "while sleep 3600; do :; done"]
networks:
    app-network:
        driver: bridge
