version: "3"
services:
    client:
        container_name: benchmark-client
        image: quaddo/artillery:latest
        restart: 'no'
        ports:
            - 8080:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        depends_on:
            - nginx
    base:
        image: quaddo/artillery:latest
        container_name: benchmark-base
        restart: 'no'
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        entrypoint: ["sh","-c","while sleep 3600; do :; done"]
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
