version: "3"
services:
    client:
        image: loadimpact/k6:0.29.0
        container_name: benchmark-client
        restart: "no"
        ports:
            - 8080:8080
        environment:  
            SCRIPT: |
                const http = require('k6/http')
                export default function () {
                http.get('http://172.31.3.99')
                }
        entrypoint:
            [
                "sh",
                "-c",
                # 'echo "$$SCRIPT" > ~/script.js; k6 run --vus=1 --duration=10s ~/script.js',
                # 'echo "$$SCRIPT" > ~/script.js; k6 run --vus=5 --duration=10s ~/script.js',
                # 'echo "$$SCRIPT" > ~/script.js; k6 run --vus=10 --duration=10s ~/script.js',
                'echo "$$SCRIPT" > ~/script.js; k6 run --vus=30 --duration=120s ~/script.js',
                # 'echo "$$SCRIPT" > ~/script.js; k6 run --vus=30 --duration=30s --compatibility-mode=base ~/script.js',
                # 'echo "$$SCRIPT" > ~/script.js; k6 run --vus=30 --duration=30s ~/script.js',
            ]
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "16"
                    memory: 31g
    base:
        image: loadimpact/k6:0.29.0
        container_name: benchmark-base
        restart: 'no'
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1g
        entrypoint: ["sh","-c","while sleep 3600; do :; done"]
networks:
    app-network:
        driver: bridge
