version: "3"
services:
    hey:
        image: loadimpact/k6:0.29.0
        container_name: benchmark-client
        restart: "no"
        ports:
            - 8080:8080
        environment:
            SCRIPT: |
                const http = require('k6/http')
                export default function () {
                http.get('http://nginx')
                }
        entrypoint:
            [
                "sh",
                "-c",
                'echo "$$SCRIPT" > ~/script.js; sleep 10 && k6 run --vus=1000 --iterations=1000 ~/script.js && sleep 10',
            ]
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
