version: "3"
services:
    benchmark-client:
        image: egaillardon/jmeter:latest
        container_name: benchmark-client
        restart: 'no'
        ports:
            - 8080:8080
        networks:
            - app-network
        # environment:
            # DISPLAY: :0.0
        entrypoint: ["sh","-c","while sleep 3600; do :; done"]
        # entrypoint:
        #     [
        #         "sh",
        #         "-c",
        #         "jmeter",
        # #         # "-h"
        #         # "-n",
        #         # "–t",
        #         # "test.jmx",
        #         # "-l",
        #         # "testresults.jtl",
        #     ]
        deploy:
            resources:
                limits:
                    cpus: "16"
                    memory: 32g
    base:
        image: egaillardon/jmeter:latest
        container_name: benchmark-base 
        restart: 'no'
        ports:
            - 8081:8080
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1g
networks:
    app-network:
        driver: bridge
