version: "3"
services:
    benchmark-client:
        image: rdpanek/jmeter:latest
        container_name: benchmark-client
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - app-network
        # environment:
            # DISPLAY: :0.0
        entrypoint:
            [
                "sh",
                "-c",
                "jmeter",
        #         # "-h"
                # "-n",
                # "–t",
                # "test.jmx",
                # "-l",
                # "testresults.jtl",
            ]
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
