version: "3"
services:
    benchmark-client:
        build: .
        # image: gobenchmark/drill:latest
        container_name: benchmark-client
        restart: "no"
        ports:
            - 8080:8080
        environment:
            SCRIPT: |
                concurrency: 1000
                base: 'http://nginx'
                iterations: 1000
                rampup: 2

                plan:
                - name: Fetch nginx page
                    request:
                    url: /
        entrypoint:
            [
                "sh",
                "-c",
                'echo "$$SCRIPT" > ~/benchmark.yml; /usr/local/bin/drill --benchmark ~/benchmark.yml --stats',
            ]
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        depends_on:
            - nginx
    base:
        image: alpine:20190707
        container_name: benchmark-base
        restart: 'no'
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        command: ["sh","-c","while sleep 3600; do :; done"]
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
