version: "3"
services:
    benchmark-client:
        # build: .
        image: gobenchmark/drill:latest
        container_name: benchmark-client
        restart: "no"
        ports:
            - 8080:8080
        environment:
            SCRIPT: |
                concurrency: 1000
                base: 'http://nginx'
                iterations: 1000
                rampup: 2

                plan:
                - name: Fetch nginx page
                    request:
                    url: /
        entrypoint:
            [
                "sh",
                "-c",
                'echo "$$SCRIPT" > ~/benchmark.yml; sleep 10 && /usr/local/bin/drill --benchmark ~/benchmark.yml --stats && sleep 10',
            ]
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "3"
                    memory: 6g
                reservations:
                    cpus: "0.5"
                    memory: 1g
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
